### ISSUE TITLE
建议不要修改推特个人简介

### ISSUE THREAD

**Issue by Hans0312** [ninjahome/web-bridge#18]
![截屏2024-01-24 下午5 04 26](https://github.com/ninjahome/web-bridge/assets/40728426/2fb85236-6478-4657-a8b7-c775ca99ff58)
建议用户绑定推特时不要修改用户的个人简介内容，很多用户精心在推特上写的自我简介、个人主页等等，不希望被覆盖

**Comment by hopwesley** [comment]
fixed
