### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by udou2019** [ninjahome/web-bridge#20]
<img width="786" alt="image" src="https://github.com/ninjahome/web-bridge/assets/54393010/57fab3da-b9bf-439d-9baa-7c84c0b0c325">
<img width="424" alt="image" src="https://github.com/ninjahome/web-bridge/assets/54393010/2b091931-ea46-47ac-8d57-97368206a86c">
<img width="902" alt="image" src="https://github.com/ninjahome/web-bridge/assets/54393010/85b5e809-d34c-47fe-a033-79eb8a39e6e4">
![image](https://github.com/ninjahome/web-bridge/assets/54393010/4669d3e2-543a-43ea-bc52-da6995545067)
<img width="902" alt="image" src="https://github.com/ninjahome/web-bridge/assets/54393010/f89b9856-86b6-4787-ab0a-dcde94144381">
<img width="781" alt="image" src="https://github.com/ninjahome/web-bridge/assets/54393010/184be22f-5b93-4665-ac59-5388bb724b4b">
<img width="756" alt="image" src="https://github.com/ninjahome/web-bridge/assets/54393010/c58e5fce-c3c8-404e-9722-17ede2cce043">

**Comment by hopwesley** [comment]
fixed
