### ISSUE TITLE
排行榜功能优化

### ISSUE THREAD

**Issue by Hans0312** [ninjahome/web-bridge#29]
![截屏2024-01-25 下午4 49 08](https://github.com/ninjahome/web-bridge/assets/40728426/7b3b4811-d6df-49ab-8c68-ed93a4e8fe0b)
希望在本期的票排行榜、最佳创作者排行榜以及大户荣誉榜中，可以做到鼠标放到这个人的头像上时能出来“查看详情”的按钮，方便用户进入其主页查看这个人具体情况

**Comment by hopwesley** [comment]
fixed
