### ISSUE TITLE
Different  Vote Amount 

### ISSUE THREAD

**Issue by Hans0312** [ninjahome/web-bridge#30]
![截屏2024-01-25 下午4 52 57](https://github.com/ninjahome/web-bridge/assets/40728426/27c828dc-90ec-40ab-b0b1-05ec0c8b3393)
![截屏2024-01-25 下午4 53 23](https://github.com/ninjahome/web-bridge/assets/40728426/d59e95b5-81d0-4574-8b55-53cb31e9e043)

At the same time, the vote amount on the home page is different from that on "my lottery" page

**Comment by hopwesley** [comment]
fixed
